### ISSUE TITLE
DEL in filter edit box deletes items from list

### ISSUE THREAD

**Issue by liqube** [medo64/Bimil#5]
When you press DEL in the filter edit box (instead of backspace) when editing the filter the first selected item is **deleted from the account list**, and forever lost if saved after accidentally. Press DEL several times in a row you delete quite a few accounts.

**Comment by medo64** [comment]
Thank you for this report. While not necessarily a bug, I agree that it's a dangerous thing. Corrected in the latest release (2.84).
